//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_xgah8k
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class webshop_database1Entities : DbContext
    {
        public webshop_database1Entities()
            : base("name=webshop_database1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Megrendelo> Megrendelo { get; set; }
        public virtual DbSet<Rendeles> Rendeles { get; set; }
        public virtual DbSet<Rendeles_tetel> Rendeles_tetel { get; set; }
        public virtual DbSet<Szallitas> Szallitas { get; set; }
        public virtual DbSet<Szamla> Szamla { get; set; }
        public virtual DbSet<Termek> Termek { get; set; }
    }
}
