//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_xgah8k
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles_tetel
    {
        public int Rend_tetel_id { get; set; }
        public int Termek_fk { get; set; }
        public int Rendeles_fk { get; set; }
        public int Darab { get; set; }
    
        public virtual Rendeles Rendeles { get; set; }
        public virtual Termek Termek { get; set; }
    }
}
