//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_xgah8k
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendeles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rendeles()
        {
            this.Rendeles_tetel = new HashSet<Rendeles_tetel>();
        }
    
        public int Rendeles_id { get; set; }
        public int Login_fk { get; set; }
        public int Szallitas_fk { get; set; }
        public int Szamla_fk { get; set; }
        public string Fizetes { get; set; }
        public System.DateTime Datum { get; set; }
    
        public virtual Megrendelo Megrendelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles_tetel> Rendeles_tetel { get; set; }
        public virtual Szallitas Szallitas { get; set; }
        public virtual Szamla Szamla { get; set; }
    }
}
