//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_xgah8k
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szamla
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szamla()
        {
            this.Rendeles = new HashSet<Rendeles>();
        }
    
        public int Szamla_id { get; set; }
        public string Vezeteknev { get; set; }
        public string Keresztnev { get; set; }
        public int Iranyitszam { get; set; }
        public string Utca { get; set; }
        public int Hazszam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles> Rendeles { get; set; }
    }
}
