//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beadando_xgah8k
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Termek()
        {
            this.Rendeles_tetel = new HashSet<Rendeles_tetel>();
        }
    
        public int Termek_id { get; set; }
        public string Termek_nev { get; set; }
        public string Szin { get; set; }
        public int Ar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendeles_tetel> Rendeles_tetel { get; set; }
    }
}
